# -*- coding: utf-8 -*-
"""ML Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aGWJrHEHTf9VmsNOvkAjSIzgPz1nSVvX
"""

import numpy as np
a= np.random.randint(low=1, high=21, size=15)
a= a.reshape(3, 5)
print("Array shape:", a.shape)
a[a.argmax(axis=1), np.arange(a.shape[0])] = 0
print(a)

import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
print("Array shape:", b.shape)
print("Array type:", type(b))
print("Array data type:", b.dtype)
print(b)

import numpy as np
c = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(c)
print("Eigenvalues", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)

import numpy as np
d= np.array([[0, 1, 2], [3, 4, 5]])
sum= np.trace(d)
print("Sum of diagonal elements/TRace:", sum)

import numpy as np
e= np.array([[1, 2], [3, 4], [5, 6]])

f= e.reshape((2, 3))
print("Original array:\n", e)
print("Reshaped array:\n", f)

import numpy as np
g = np.array([[1, 2, 3], [4, 5, 6]])
h= g.reshape((3, 2))
print("Original array:\n", g)
print("Reshaped array:\n", h)

import matplotlib.pyplot as plt

languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]
plt.pie(popularity, labels=languages, autopct='%1.1f%%')
plt.show()